TpDojo.Web/Controllers/ArmesController.cs
namespace TpDojo.Web.Controllers;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using TpDojo.Business;
using TpDojo.Web.Models;

public class ArmesController : Controller
{
    private readonly ArmeService armeService;

    public ArmesController(ArmeService armeService) => this.armeService = armeService;

    // GET: Armes
    public async Task<IActionResult> Index()
    {
        var armeDtos = await this.armeService.GetArmesAsync();
        var armes = ArmeViewModel.FromArmes(armeDtos);
        return this.View(armes);
    }

    // GET: Armes/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var arme = await this.armeService.GetArmeByIdAsync(id);
        if (arme == null)
        {
            return this.NotFound();
        }

        return this.View(ArmeViewModel.FromArmeDto(arme));
    }

    // GET: Armes/Create
    public IActionResult Create()
    {
        return this.View();
    }

    // POST: Armes/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ArmeViewModel arme)
    {
        if (this.ModelState.IsValid)
        {
            await this.armeService.AddArmeAsync(ArmeViewModel.ToArmeDto(arme));
            return this.RedirectToAction(nameof(Index));
        }
        return this.View(arme);
    }

    // GET: Armes/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var arme = await this.armeService.GetArmeByIdAsync(id);
        if (arme == null)
        {
            return this.NotFound();
        }
        return this.View(ArmeViewModel.FromArmeDto(arme));
    }

    // POST: Armes/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, ArmeViewModel arme)
    {
        if (id != arme.Id)
        {
            return this.NotFound();
        }

        if (this.ModelState.IsValid)
        {
            try
            {

                var armeDto = ArmeViewModel.ToArmeDto(arme);
                await this.armeService.UpdateArmeAsync(armeDto);

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this.ArmeExistsAsync(arme.Id))
                {
                    return this.NotFound();
                }
                else
                {
                    throw;
                }
            }
            return this.RedirectToAction(nameof(Index));
        }
        return this.View(arme);
    }

    // GET: Armes/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var arme = await this.armeService.GetArmeByIdAsync(id);
        if (arme == null)
        {
            return this.NotFound();
        }

        return this.View(ArmeViewModel.FromArmeDto(arme));
    }

    // POST: Armes/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var result = await this.armeService.RemoveArmeAsync(id);
        if (!result)
        {
            this.ModelState.AddModelError("", "L'arme est associée à un samourai, veuillez supprimer la relation");
            var arme = await this.armeService.GetArmeByIdAsync(id);

            return this.View(ArmeViewModel.FromArmeDto(arme));
        }
        return this.RedirectToAction(nameof(Index));
    }

    private async Task<bool> ArmeExistsAsync(int id)
    {
        return await this.armeService.ArmeExistsAsync(id);
    }
}

TpDojo.Web/Controllers/SamouraisController.cs
namespace TpDojo.Web.Controllers;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using TpDojo.Business;
using TpDojo.Web.Models;

public class SamouraisController : Controller
{
    private readonly SamouraiService samouraiService;
    private readonly ArmeService armeService;
    private readonly ArtMartialService artMartialService;

    public SamouraisController(SamouraiService samouraiService, ArmeService armeService, ArtMartialService artMartialService)
    {
        this.samouraiService = samouraiService;
        this.armeService = armeService;
        this.artMartialService = artMartialService;
    }

    // GET: Samourais
    public async Task<IActionResult> Index()
    {
        var samouraiDtos = await this.samouraiService.GetSamouraisAsync();
        var armes = SamouraiViewModel.FromSamourais(samouraiDtos);
        return this.View(armes);
    }

    // GET: Samourais/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var samourai = await this.samouraiService.GetSamouraiByIdAsync(id);
        if (samourai == null)
        {
            return this.NotFound();
        }

        return this.View(SamouraiViewModel.FromSamouraiDto(samourai));
    }

    // GET: Samourais/Create
    public async Task<IActionResult> Create()
    {
        await this.ChargerListesAsync();
        return this.View();
    }

    // POST: Samourais/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(SamouraiFormViewModel samourai)
    {
        if (this.ModelState.IsValid)
        {
            var samouraiDto = SamouraiFormViewModel.ToSamouraiDto(samourai);

            await this.samouraiService.AddSamouraiAsync(samouraiDto, samourai.ArmeId, samourai.ArtMartiauxIds);
            return this.RedirectToAction(nameof(Index));
        }
        return this.View(samourai);
    }

    // GET: Samourais/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var samourai = await this.samouraiService.GetSamouraiByIdAsync(id);
        if (samourai == null)
        {
            return this.NotFound();
        }
        await this.ChargerListesAsync();
        return this.View(SamouraiFormViewModel.FromSamouraiDto(samourai));
    }

    // POST: Samourais/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, SamouraiFormViewModel samourai)
    {
        if (id != samourai.Id)
        {
            return this.NotFound();
        }

        if (this.ModelState.IsValid)
        {
            try
            {
                await this.samouraiService.UpdateSamouraiAsync(SamouraiFormViewModel.ToSamouraiDto(samourai), samourai.ArmeId, samourai.ArtMartiauxIds);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await this.SamouraiExists(samourai.Id))
                {
                    return this.NotFound();
                }
                else
                {
                    throw;
                }
            }
            return this.RedirectToAction(nameof(Index));
        }
        return this.View(samourai);
    }

    // GET: Samourais/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return this.NotFound();
        }

        var samourai = await this.samouraiService.GetSamouraiByIdAsync(id);
        if (samourai == null)
        {
            return this.NotFound();
        }

        return this.View(SamouraiViewModel.FromSamouraiDto(samourai));
    }

    // POST: Samourais/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await this.samouraiService.RemoveSamouraiAsync(id);
        return this.RedirectToAction(nameof(Index));
    }

    private async Task<bool> SamouraiExists(int id)
    {
      return await this.samouraiService.SamouraiExistsAsync(id);
    }

    private async Task ChargerListesAsync()
    {
        this.ViewData["Armes"] = ArmeViewModel.FromArmes(await this.armeService.GetArmesWithoutSamouraiAsync());
        this.ViewData["ArtMartiaux"] = ArtMartialViewModel.FromArtMartiaux(await this.artMartialService.GetArtMartiauxAsync());
    }
}

TpDojo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TpDojo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TpDojo.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TpDojo.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Samourais" asp-action="Index">Samourais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Armes" asp-action="Index">Armes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArtMartiaux" asp-action="Index">Art martiaux</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TpDojo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>